### ISSUE TITLE
install has issues

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-installer#1]
I did 2 installs using Debian
both end with the following and do no load GUI

------------------------------------------------------------------------------
install ffplayout-frontend
------------------------------------------------------------------------------
/home/accounts/v1.5/ffplayout-installer/scripts/frontend.sh: line 17: wget: command not found
tar: v2.1.5.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'ffplayout-frontend-2.1.5': No such file or directory
rm: cannot remove 'v2.1.5.tar.gz': No such file or directory
/home/accounts/v1.5/ffplayout-installer/scripts/frontend.sh: line 21: cd: ffplayout-frontend: No such file or di
rectory
ln: target '/var/www/ffplayout-frontend/static/' is not a directory: No such file or directory
npm WARN saveError ENOENT: no such file or directory, open '/var/www/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/var/www/package.json'
npm WARN www No description
npm WARN www No repository field.
npm WARN www No README data
npm WARN www No license field.
up to date in 0.364s
found 0 vulnerabilities
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /var/www/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-13T08_50_46_959Z-debug.log
cp: cannot stat 'docs/ffplayout.conf': No such file or directory
sed: can't read /etc/nginx/sites-available/ffplayout.conf: No such file or directory
sed: can't read /etc/nginx/sites-available/ffplayout.conf: No such file or directory
Job for nginx.service failed.
See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by jb-alvarado** [comment]
Have you not run the **install.sh** script? The script normally installs all needed packages and your error message says, that wget is missing - which should be installed by the script first.

**Comment by edwoodza** [comment]
yup script run (way easier btw with 1 command) 
this was on Debian. yesterday i found Ubuntu worked better for docker. so maybe its OS related?
