### ISSUE TITLE
Unit ffplayout-engine.service could not be found.

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#10]
Hi everything is installed but when I try to start the playout it doesn't start. Then I tried this command to check the status systemctl status ffplayout-engine, the result of this command is this " Unit ffplayout-engine.service could not be found

**Comment by jb-alvarado** [comment]
The status you have to check with: `systemctl status ffplayout_engine`

Is there anything in the logs?

**Comment by goldencrowe** [comment]
The playout engine is running right now, but when I click the play button in the player its not running the playlist
![error](https://user-images.githubusercontent.com/94108787/144492049-3ea2cbc9-ae35-4b02-a9de-499bd643cc2e.png)

**Comment by jb-alvarado** [comment]
Maybe your `player_url` is not set correctly? Should be something like: `https://example.org/live/tv.m3u8`

The log show, that there is no playlist and that you have to create them.

**Comment by goldencrowe** [comment]
I have checked the player_url its ok. I have also fixed the playlist error by pointing it to the right directory
![not playing](https://user-images.githubusercontent.com/94108787/144501925-4678811b-bf3e-4dac-b385-8e0ae5ead1a9.png)
Could you please take a look at his picture, when i press the play button nothing happens.

**Comment by jb-alvarado** [comment]
What says the Browser console log?

**Comment by goldencrowe** [comment]
![4](https://user-images.githubusercontent.com/94108787/144504894-1212621a-55bd-43a8-b0ef-34d9d5589e8b.png)

**Comment by jb-alvarado** [comment]
No I mean the console log from firefox or chrome.

**Comment by goldencrowe** [comment]
I didn't see any log in the console from Firefox and chrome. This is the problem I am facing right now. The playlist is playing, but cannot view in the player. The player is just loading. I tried the player url in VLC its not playing too. 
![66](https://user-images.githubusercontent.com/94108787/144575893-11f4cc0d-e97e-43cd-ae56-923660aa40ef.png)

**Comment by jb-alvarado** [comment]
Normal you have to open den console, activate every output, reload the page and click the play button. Then it should come something.

How is your playout config? Specially the output settings? And your gui config?

**Comment by goldencrowe** [comment]
![77](https://user-images.githubusercontent.com/94108787/144582608-5a2bbe9b-4108-4f4e-92ce-1d80ef492ca3.png)
playout config

**Comment by goldencrowe** [comment]
![Uploading 88.png…]()

**Comment by goldencrowe** [comment]
out:
    helptext: The final playout compression. Set the settings to your needs. 'mode'
        has the standard options 'desktop', 'hls', 'stream'. Self made outputs can
        be define, by adding script in output folder with an 'output' function inside.
        'stream_output' is for streaming output, two ffmpeg instances are fired up,
        for pre- and post-processing. 'hls_output' is for direct output to hls playlist,
        without pre- and post-processing, mode must be 'hls'.
    mode: stream
    service_name: Live Stream
    service_provider: example.org
    ffmpeg_param: -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 800k -bufsize 1500k -preset medium -profile:v Main -level 3.1 -c:a
        aac -ar 44100 -b:a 128k
    stream_output: -flags +global_header -f flv rtmp://localhost/live/stream
    hls_output: -flags +cgop -f hls -hls_time 6 -hls_list_size 600 -hls_flags append_list+delete_segments+omit_endlist+program_date_time
        -hls_segment_filename /var/www/srs/live/stream-%09d.ts /var/www/srs/live/stream.m3u8

**Comment by goldencrowe** [comment]
![88](https://user-images.githubusercontent.com/94108787/144583038-5ce39649-817b-4c09-a1f0-8e9415d5ac25.png)

**Comment by jb-alvarado** [comment]
Can you play the rtmp stream? For example with: `ffplay rtmp://example.org/live/stream`.
What says: `systemctl status srs`?

Is there files under: `/var/www/srs/live`?

At the moment you will get only a black picture with noise in sound, because your playlist is not full enough.

**Comment by goldencrowe** [comment]
![srs](https://user-images.githubusercontent.com/94108787/144610892-d38af05f-c5ca-4c22-b2d9-713af98b16c3.png)
systemctl status srs

**Comment by goldencrowe** [comment]
Yes there are files in /var/www/srs/live

**Comment by jb-alvarado** [comment]
Can you post your nginx ffplayout config? But please in a code block.

**Comment by goldencrowe** [comment]
Could you please tell me how to do that.

**Comment by jb-alvarado** [comment]
Past the content from `/etc/nginx/sites-enabled/ffplayout.conf` here, in a code block, starting and ending with: **```**

**Comment by goldencrowe** [comment]
`server {
    listen 80;

    server_name 13.250.113.214:3000;

    gzip on;
    gzip_types text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;

    charset utf-8;

    client_max_body_size 7000M; # should be desirable value

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location / {
        if ($http_origin ~ '^https?://(localhost|13\.250\.113\.214:3000)') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
        }

        if ($request_method = OPTIONS ) {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        root /var/www/ffplayout-frontend/dist/;

    }

    location ~ ^/(api|admin|auth|api-auth) {
        if ($http_origin ~ '^https?://(localhost|13\.250\.113\.214:3000)') {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
        }

        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
 proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 36000s;
        proxy_connect_timeout 36000s;
        proxy_send_timeout 36000s;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        send_timeout 36000s;
        proxy_no_cache 1;
        proxy_pass http://127.0.0.1:8001;

    }

    location /static/ {
        alias /var/www/ffplayout-api/ffplayout/static/;
    }

     location /live/ {
        alias /var/www/srs/live/;
    }
}


`

**Comment by goldencrowe** [comment]
```
server {
listen 80;

server_name 13.250.113.214:3000;

gzip on;
gzip_types text/plain application/xml text/css application/javascript;
gzip_min_length 1000;

charset utf-8;

client_max_body_size 7000M; # should be desirable value

add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

location / {
    if ($http_origin ~ '^https?://(localhost|13\.250\.113\.214:3000)') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
    }

    if ($request_method = OPTIONS ) {
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
    }

    root /var/www/ffplayout-frontend/dist/;

}

location ~ ^/(api|admin|auth|api-auth) {
    if ($http_origin ~ '^https?://(localhost|13\.250\.113\.214:3000)') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
    }

    add_header Last-Modified $date_gmt;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    if_modified_since off;
    expires off;
    etag off;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_read_timeout 36000s;
proxy_connect_timeout 36000s;
proxy_send_timeout 36000s;
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
send_timeout 36000s;
proxy_no_cache 1;
proxy_pass http://127.0.0.1:8001;

}

location /static/ {
    alias /var/www/ffplayout-api/ffplayout/static/;
}

 location /live/ {
    alias /var/www/srs/live/;
}
}

```

**Comment by jb-alvarado** [comment]
Should be fine. I was also able to play the address: http://your ip/live/stream.m3u8. On Monday I will install a ubuntu VM and try to reproduce.

**Comment by goldencrowe** [comment]
ok that would be very helpful. Thank you brother.

**Comment by goldencrowe** [comment]
Hi have you got any new info regarding my issue

**Comment by jb-alvarado** [comment]
Oh, sorry, I thought you have it already. I tested on a Ubuntu 20.04 VM and there it was working.

Can you try again on a fresh machine from master repo with:

```
./install.sh \
    --domain=[domain name or IP] \
    --nginx=y \
    --https=n \
    --ffmpeg=y \
    --srs=y \
    --channels=n \
    --user=[username] \
    --password=[password]
```

**Comment by goldencrowe** [comment]
Thank you, I will try and let you know.
