### ISSUE TITLE
How to connect to rtmp output to youtube

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#12]
Hi, in the stream ouput section I have put this command -flags +global_header -f flv rtmp://a.rtmp.youtube.com/live2/[my stream key]
but this is not connecting my playout to Youtube. Could you please take a look at this, thank you.

**Comment by goldencrowe** [comment]
I am using the ffplayout in an AWS instance. Are there any ports to be opened.

**Comment by goldencrowe** [comment]
![image](https://user-images.githubusercontent.com/94108787/144741222-f177da21-1c11-4e2e-891f-107f8fc670ef.png)

**Comment by jb-alvarado** [comment]
There was a breaking change in ffmpeg. When you use the compiled version from this script, you have to update the engine, or build everything from the beginning.
