### ISSUE TITLE
How to connect to Youtube live

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#14]
Hi could you please help me to connect our ffplayout to Youtube live. Thank you.

**Comment by goldencrowe** [comment]
Also is there any way to reduce cpu load and buffering

**Comment by jb-alvarado** [comment]
> Hi could you please help me to connect our ffplayout to Youtube live. Thank you.

What is the problem? When something is not working, is good to follow this steps:
1. try to stream from the machine directly with ffmpeg to your target and see if this is working.
2. clone test [clips and playlist](https://github.com/ffplayout/test-clips.git) in the same parent folder where ffplayout_engine is located, e.g. **/opt/**
2. stop ffplayout engine service and run ffplayout_engine from terminal with:
    - `cd /opt/ffplayout_engine`
    -  `./ffplayout.py -l none -s now -t none -m stream -p ../test-clips/_playlist.json`
    - when this works, run: `./ffplayout.py -l none -s 00:00:00 -t 24:00:00 -m stream -p ../test-clips/_playlist.json`
    - when this also works, run with your playlist and config: `./ffplayout.py -l none`
    - Watch always the output, normally it should say what's wrong.

> Also is there any way to reduce cpu load and buffering

From which buffering are you talking? There should not be any noticeable buffering. There will be only a delay when playing HLS, but that is in the nature of HLS and can/must be tweak there.

**Comment by jb-alvarado** [comment]
And always check if your files are not corrupt and readable by ffmpeg.
