### ISSUE TITLE
RTMP out is ok, but the ffplayout playout frontend player and player url doesn't work

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#15]
Hi RTMP out is working perfectly, but the player url always loops in a particular section of the video and it isn't showing whats playing in the playlist. But everything is perfect with the RTMP out

VIDEOJS: WARN: Problem encountered with playlist 0-https://******/live/stream.m3u8. Trying again since it is the only playlist.

I have also seen this above error.

**Comment by jb-alvarado** [comment]
Hi,\
good to hear that rtmp output works now! Can you explain what was the problem?

Do you stream now to the local rtmp server or to youtube? I don't now if I explain it the last time correctly, but if you want to have preview and stream to youtube I would recommend to stream to the local rtmp server and from there forward to youtube. It will give you maybe a delay of 2 seconds, but I think is no problem.

you could add a transcode section to the srs config:

```
transcode live/stream {
        enabled     on;
        ffmpeg      /usr/local/bin/ffmpeg;

        engine youtube {
            enabled         on;
            iformat         live_flv;
            vfilter {
                v           error;
            }

            vcodec          copy;
            acodec          copy;
            oformat         flv;
            output          rtmp://[youtube address];
        }
    }
```
You can add multiple engines to stream to multiple platforms.

But to your problem: Is there ***.ts** files under `/var/www/srs/live/`? And is there also a **stream.m3u8** playlist?

**Comment by goldencrowe** [comment]
Hi thanks for your prompt reply. I am streaming it directly from the ffplayout to Youtube. The problem is I cannot preview whats happening realtime in the player inside the ffplayout frontend. The player inside the frontend and the stream.m3u8 is always playing a loop of video again and again. But the RTMP streamout is working perfectly. 

![image](https://user-images.githubusercontent.com/94108787/147650748-d2f9948c-6749-45df-a34d-5dbbf02742f6.png)

**Comment by jb-alvarado** [comment]
And the stream looks on youtube ok? Can I see the output part of your settings?

**Comment by goldencrowe** [comment]
![image](https://user-images.githubusercontent.com/94108787/147736663-7f3cc2a1-52b1-449b-8591-6353da9919e6.png)

**Comment by goldencrowe** [comment]
Its streaming without any problems to Youtube live. But we cannot preivew the videos using the player_url in VLC or in the FFplayout dashboard.

**Comment by goldencrowe** [comment]
![image](https://user-images.githubusercontent.com/94108787/147737057-a70b5f77-787d-409e-9e7e-c390fec01c33.png)

**Comment by jb-alvarado** [comment]
Ah ok, I though of that: You can not stream to a external source and using the internal rtmp server for previewing. You have two options, I recommend the second one:

1. Use a tee muxer, which is described here: https://github.com/ffplayout/ffplayout-installer/issues/11, to stream to youtube and your local rtmp server for preview.
2. stream to your local server (`rtmp://localhost/live/stream`) and from there forward to youtube. The config file for that should be located under: `/etc/srs/srs.conf`, when you have made a full install. The content should look like:
```nginx
listen              1935;
max_connections     20;
daemon              on;
pid                 /usr/local/srs/objs/srs.pid;
srs_log_tank        console; # file;
srs_log_file        /var/log/srs.log;
ff_log_dir          /tmp;
# can be: verbose, info, trace, warn, error
srs_log_level       error;
http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
    disk            sda vda xvda xvdb;
}
vhost __defaultVhost__ {
    # timestamp correction
    mix_correct     on;
    http_hooks {
        enabled         off;
        on_publish      http://127.0.0.1:8085/api/v1/streams;
        on_unpublish    http://127.0.0.1:8085/api/v1/streams;
    }
    transcode live/stream {
        enabled     on;
        ffmpeg      /usr/local/bin/ffmpeg;

        engine youtube {
            enabled         on;
            iformat         live_flv;
            vfilter {
                v           error;
            }

            vcodec          copy;
            acodec          copy;
            oformat         flv;
            output          rtmp://-----youtube address-----;
        }
    }
    hls {
        enabled         on;
        hls_path        /var/www/srs;
        hls_fragment    6;
        hls_window      3600;
        hls_cleanup     on;
        hls_dispose     0;
        hls_m3u8_file   live/stream.m3u8;
        hls_ts_file     live/stream-[seq].ts;
        }
}
```

**Comment by goldencrowe** [comment]
Hi thank you, it got fixed. Thank you.
