### ISSUE TITLE
Audio video sync out issue

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#16]
Hi I am facing a strange issue, when I stream to Youtube, after some time the audio and video is having a sync out issue.

**Comment by jb-alvarado** [comment]
Hello,\
how have you fix the preview issue? Is the preview in sync?

**Comment by goldencrowe** [comment]
I have streamed the rtmp to a local server like you said and from there streamed to Youtube. Its working fine. Now there is no sync issue. I think it was caused by a corrupted file, that I have uploaded.

**Comment by jb-alvarado** [comment]
Ok, thank you for the info. When files are corrupted, most time you see it in the decoder.log.

**Comment by goldencrowe** [comment]
It was caused by a file that we have uploaded. Sorted it out. Thank you.
