### ISSUE TITLE
Installer set up

### ISSUE THREAD

**Issue by tvadi** [ffplayout/ffplayout-installer#17]
For domain, do I just put: localhost or 127.0.0.1  ?  or any non-public IP like 10.0.0.1?

**Comment by tvadi** [comment]
After running the installer and trying 10.50.0.1 for the domain, the web GUI does not load.  What am I missing?  Thanks-

**Comment by jb-alvarado** [comment]
When you are using the IP instead of a domain, you have to use the IP from the Maschine where the ffplayout is running on.

**Comment by tvadi** [comment]
Ok got it to install, needed npm, machine IP, and nginx
