### ISSUE TITLE
Strange problem when installing

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#18]
Hi when I try to install the ffplayout it  shows this error

WARNING: this will remove all apps releated to ffplayout: SRS, frontend, API and engine.
But from nginx only the config will be removed and ffmpeg will stay also in place.

Do you want to continue? (Y/n) 

if it Hit Yes or No, its uninstalling. Cannot install with ./install.sh

**Comment by jb-alvarado** [comment]
Sorry, is fixed now.
