### ISSUE TITLE
Unit ffplayout_engine.service could not be found.

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#19]
Hi I am facing another issue when installing, everything installs but the playout doesn't run. When I put this command systemctl status ffplayout_engine, I am getting this result Unit ffplayout_engine.service could not be found. Could you please take a look, thank you.

**Comment by jb-alvarado** [comment]
Please try again, with the new installer version

**Comment by goldencrowe** [comment]
Hi I have tried the latest installer, it got installed but rtmp out is not working, when I checked the ffmpeg is not running.

**Comment by jb-alvarado** [comment]
I just tried the installer and everything run normal. The systemd unit should be under: **/etc/systemd/system/**.

**Comment by goldencrowe** [comment]
ok let me try once again. Thank you.

**Comment by goldencrowe** [comment]
Hi I am getting this page after installation, its not showing the ffplayout frontend

![image](https://user-images.githubusercontent.com/94108787/149126716-8e4d5bd9-bbb4-4283-a6fa-9c6db928d05a.png)

**Comment by jb-alvarado** [comment]
Is this a fresh and clean system, or do you have already nginx installed?

What OS are you using?

**Comment by goldencrowe** [comment]
Its a fresh and clean system, I am installing it on cloud. OS is Debian 10

**Comment by goldencrowe** [comment]
the previous version is working fine, that is 3.5.0.

**Comment by goldencrowe** [comment]
Brother what all changes you have brought in the new updates?

**Comment by jb-alvarado** [comment]
Ok, strange. Can you check if under **/etc/nginx/sites-enabled** the config **ffplayout.conf** exists and that it is the only config file in that folder.

**Comment by jb-alvarado** [comment]
Maybe also restart nginx service.

**Comment by goldencrowe** [comment]
ok let me try

**Comment by parkerbrother1** [comment]
@goldencrowe 
I have run into these sorts of issues before and the solution is to make sure nodejs is installed ahead of time.
These are the steps I go through before attempting to run this installer:

```
sudo apt-get install gcc g++ make
sudo apt install build-essential

sudo cp /etc/apt/sources.list /etc/apt/sources.list~
sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
sudo apt-get update
sudo apt build-dep ffmpeg

#### Install nodejs ####
# Using Ubuntu #
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root #
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs
```

After that, you shouldn't have any installation issues.

**Comment by jb-alvarado** [comment]
As I know node should be on version 14.
