### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-installer#2]
Install on a clean machine did not successfully complete

![native install err1](https://user-images.githubusercontent.com/8553968/104577889-acc04e80-5662-11eb-8d70-bece2f4cfd0d.png)
![native install err2](https://user-images.githubusercontent.com/8553968/104577892-adf17b80-5662-11eb-8990-af1c2363ffe8.png)

**Comment by jb-alvarado** [comment]
Yes I saw this on ubuntu systems, is not related to the install script, something is happen with the node-sass package. Maybe a update of this packages helps.

**Comment by edwoodza** [comment]
am trying again with debian9 and will revert

**Comment by jb-alvarado** [comment]
Take debian10

**Comment by edwoodza** [comment]
> 
> 
> Take debian10

tried 2x with it yesterday and failed hence why i went with 9 this time.

**Comment by edwoodza** [comment]
tried Debian 10 now same errors as i posted above
plus cant connect to GUI :8088

![native install err3 debian 10](https://user-images.githubusercontent.com/8553968/104590090-7c34e080-5673-11eb-8661-479380cb41e6.png)

**Comment by jb-alvarado** [comment]
Please read a bit the logging it says everything what you need to know: **wget: command not found**, wget should be installed, when you run the script correctly.

It looks like, that you have not run `install.sh`

The standalone version works also without a given port (8088).

**Comment by edwoodza** [comment]
ran install.sh and waited 30 min for it to compile. I would assumed basic wget would be installed in debian.
will try again

**Comment by edwoodza** [comment]
ran it again no errors but not accesing it on:8088

**Comment by jb-alvarado** [comment]
You don't need to out a port behind the address.

**Comment by edwoodza** [comment]
no luck.
am going a new install again.
other than wget what other things are required by the script before.
i think this is where the issues are coming in.
the requirments before running script are they the same as the old school manual install before?

**Comment by edwoodza** [comment]
I just completed another clean install with Debian 10.
It says installation done, and did not see any errors.
But GUI does not load on the port 80 or 8088

**Comment by jb-alvarado** [comment]
I really don't now what is happen. Because every time I run the script it works perfectly. You don't have to install wget separately, just run **install.sh**, this installs everything it needed.

When you start it, set the correct domain/IP, say to everything **yes** left media and playlist path blank for taking the default paths. 

Somewhere in the middle of the process it ask for admin credentials. 

When is done, you can check the services:
- `systemctl status ffplayout-api`
- `systemctl status ffplayout-engine`
- `systemctl status nginx`

And please forget this port 8088, this is only for the docker version.

**Comment by edwoodza** [comment]
i see the script should create /var/www/ffplayout-frontend/static/opt/ffplayout
this folder does not exist after the install. so maybe part of issue?

**Comment by edwoodza** [comment]
re: "When you start it, set the correct domain/IP, say "

if you set this and IP or dns changes would this break it?

**Comment by edwoodza** [comment]
![native install err3 debian 10-1](https://user-images.githubusercontent.com/8553968/104702492-bf985900-571e-11eb-8ca0-5897b9351dbd.png)
![native install err3 debian 10-2](https://user-images.githubusercontent.com/8553968/104702497-c0c98600-571e-11eb-8435-dbaaa622ff0a.png)
![native install err3 debian 10-3](https://user-images.githubusercontent.com/8553968/104702501-c2934980-571e-11eb-96a1-c904aaac8a34.png)

**Comment by jb-alvarado** [comment]
I can not test this, so I can not say what will not work after, but yes I think not everything will work.

When you leaf the paths as default, you should have under /var/www/ffplayout-frontend/static:
```
...
lrwxrwxrwx  1 www-data www-data   13 Jan 15 09:26 tv-media -> /opt/tv-media
```

**Comment by edwoodza** [comment]
> /var/www/ffplayout-frontend/static:

potest1-8:/var/www/ffplayout-frontend/static$ dir
README.md  favicon.ico  robots.txt  tv-media

**Comment by jb-alvarado** [comment]
I guess is ok. How looks your nginx config? Under /etc/nginx/site-enabled/ffplayout.config

And what says the nginx access and error logs?

**Comment by edwoodza** [comment]
from what i see (and what 2 other testers who are more Linux Guru than me) seems there is an issue with nginx install and config with the script.

Have tried 2 different browers plus in incognito mode.

**Comment by edwoodza** [comment]
> /etc/nginx/site-enabled/ffplayout.conf

this file is empty. nothing written in it

**Comment by jb-alvarado** [comment]
then delete it also /etc/nginx/sites-available/ffplayout.conf and copy it and make a new symlink:
```
cp /var/www/ffplayout-frontend/docs/ffplayout.conf /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/ffplayout.conf /etc/nginx/sites-enabled/
```
After that edit the file and replace ffplayout.local with correct dns/IP
In the location areas you have to escape the dots like 192\.168\.122\.2

**Comment by edwoodza** [comment]
> ln -s /etc/nginx/sites-available/ffplayout.conf /etc/nginx/sites-enabled/

returned:

ln: failed to create symbolic link '/etc/nginx/sites-enabled/ffplayout.conf': File exists

**Comment by edwoodza** [comment]
On setup i speciaified server DNS name. but when i review the ffplayout.conf file it has "server_name ffplayout.local"
So seems it defaults to that OR because i used a servername.com there?

**Comment by jb-alvarado** [comment]
> > /etc/nginx/site-enabled/ffplayout.conf
> 
> this file is empty. nothing written in it

I wrote the path wrong, so I guess the file /etc/nginx/sites-enabled/ffplayout.conf is not empty

**Comment by edwoodza** [comment]
ok let me create a new machine and retest clean (without failed previous install)

**Comment by edwoodza** [comment]
have just done new install with the update script.
cant load on port:80
nothing loads

**Comment by jb-alvarado** [comment]
but what comes when you enter the page? nginx was running the last time, so something must come, and when it is only a error message.

**Comment by edwoodza** [comment]
nothing loads at all. not even nginx default.
its like the web server is not configure or working.
basically comes back cant reach site

**Comment by jb-alvarado** [comment]
So the browser says: page not found? When the nginx service is running, something must show. I almost believe this nothing to do with the install script.

**Comment by edwoodza** [comment]
Nothing shows.
It's a clean Debian10 install on Google cloud.
So only what the script does is installed and configured on the machine.

**Comment by jb-alvarado** [comment]
I would recommend to create a local VM, with your prefer virtualization and test it there. When there it works, the problem is somewhere else, and I can not give support for that.

**Comment by edwoodza** [comment]
Done local too. 
It's why I tried cloud to eliminate local issues I may have had.

Both have same issues local and cloud.

Docket over works local and cloud so it's a set up/install/config issue, not the actual software. 

Monday I can send you ssh access if you like to check and confirm so you can see and dig into what we seeing if you like.

**Comment by edwoodza** [comment]
seems i solved it using some of the comments from ticket #3 on this thread.
testing continues now
