### ISSUE TITLE
Guide or wiki or forum?  Cannot play playlist...

### ISSUE THREAD

**Issue by tvadi** [ffplayout/ffplayout-installer#21]
I have it installed from the Docker set up, loaded the web GUI, I can load a file, loop in playlist and that fills the day with that file but nothing plays in the viewer.  Clips viewer will play but not the player on the control page.  Bit of a newbie, looking for more of a guide or any insight.  Also, it looks like with the Docker set up uses its own version on ffmpeg?  I need it to use the version I compiled that supports Decklink and libklvanc.  Any guidance would be great, thanks!

**Comment by jb-alvarado** [comment]
Ok, it should work again. Sorry for the trouble.

**Comment by tvadi** [comment]
Well now my terminal caught fire from burning up all that code in the new installer..  Just kidding!  Awesome it works and VLC works getting the stream on rtmp://192.168.1.xxx/live/stream   You rock!

**Comment by tvadi** [comment]
So I will have to use my ffmpeg compile but wanted to be sure I have everything needed for ffplayout, seems to only work with the version of ffmpeg made by the installer..  I have:

`cd ~/ffmpeg_sources
wget  https://ffmpeg.org/releases/ffmpeg-4.4.tar.bz2
tar -xvf ffmpeg-*.tar.bz2
cd ffmpeg-*/
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include -I$HOME/ffmpeg_sources/BMD_SDK/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --bindir="$HOME/bin" \
  --disable-debug \
  --disable-shared \
  --disable-doc \
  --disable-ffplay \
  --disable-sdl2 \
  --enable-gpl \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsvtav1 \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree \
  --enable-version3 \
  --enable-runtime-cpudetect \
  --enable-avfilter \
  --enable-fontconfig \
  --enable-libfribidi \
  --enable-libsoxr \
  --enable-libsrt \
  --enable-libtwolame \
  --enable-libvpx \
  --enable-openssl \
  --enable-zlib \
  --enable-libzimg \  <<< getting ERROR: zimg >= 2.7.0 not found using pkg-config
  --enable-libdav1d \   <<< getting libavcodec/libdav1d.c:148:7: error: ‘Dav1dSettings’ {aka ‘struct Dav1dSettings’}
  --enable-pic \
  --enable-libzmq \
  --enable-libklvanc\
  --enable-decklink`

I can hopefully figure out the errors with libzimg and libdav1d...
Is there anything else needed?  Thanks!
