### ISSUE TITLE
Hi our playout server is getting overloaded.

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#22]
+ 1 hidden asset
Entrypoint app [big] = b08b423.js cff311e.js a91b8d8.js c2dfdc4.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (
244 KiB).
This can impact web performance.
Assets:
  a91b8d8.js (1.88 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size excee
ds the recommended limit (1000 KiB). This can impact web performance.
Entrypoints:
  app (2.31 MiB)
      b08b423.js
      cff311e.js
      a91b8d8.js
      c2dfdc4.js

This is the log that we got. Could you please take a look. The server got overloaded after one week of use. Its been setup in AWS.

**Comment by jb-alvarado** [comment]
This warning can be safely ignore and have nothing to do with your overloaded server.

**Comment by goldencrowe** [comment]
ok
