### ISSUE TITLE
Inserting url in playlist

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#24]
Hi is there any facility the FFplayout to insert urls of videos instead of uploading video.

**Comment by jb-alvarado** [comment]
Hello,
the playlist [support](https://github.com/ffplayout/ffplayout_engine#remote-source-from-url) this, but is not implemented in the frontend.

**Comment by goldencrowe** [comment]
could you please tell me how to do this in playlist.

**Comment by jb-alvarado** [comment]
You edit the playlist and write the http source in it?

**Comment by jb-alvarado** [comment]
The new version has this feature.
