### ISSUE TITLE
v4 update issue

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-installer#27]
Hi
Ran the --update with v4 installer.
all seems to install good.
but stream output does not start.
GUI loads and works but no output.

When i go to loggin it does not load. the load line at the top does not reach 100% (same bug i saw before update after running 45 days)

cant restart the services not running either

![ff 5 april](https://user-images.githubusercontent.com/8553968/161699276-f26100ac-c9ed-4db2-b8f3-157153bf9497.png)

I rolled back to previous version and works ( v3.5.2) and all services load

appears bug in v4 installer?

Still not able to access logs. the orange load line does not load.
this likely comes from old version that had this. how do i delete logs to clear (what files need to be removed)

**Comment by edwoodza** [comment]
sorry to clarify. i did not roll back. I downloaded the previous installer v3.5.2 and used that for update.
i suspect version i had before may have been much older hence why update did not work.

am testing this now to confirm on another test machine and will advise.

**Comment by jb-alvarado** [comment]
Can you check if SRS is installed and running? The installer had here a wrong parameter. In my tests the GUI run normal.

**Comment by edwoodza** [comment]
If i recall i opted to NOT install SRS.
GUI works perfect just seems like ffmpeg and python dont start and run after update and cant be restarted either

**Comment by jb-alvarado** [comment]
Ok,
you could run: `/opt/ffplayout_engine/venv/bin/python /opt/ffplayout_engine/ffplayout.py -l none` and there you should see what is happen.

**Comment by edwoodza** [comment]
ok let me spool up a fresh testing machine and try that tomorrow morning.

**Comment by edwoodza** [comment]
I tried the command above

Traceback (most recent call last):
  File "/opt/ffplayout_engine/ffplayout.py", line 28, in <module>
    from ffplayout.utils import messenger, playout, validate_ffmpeg_libs
  File "/opt/ffplayout_engine/ffplayout/utils.py", line 246, in <module>
    _cfg = load_config()
  File "/opt/ffplayout_engine/ffplayout/utils.py", line 213, in load_config
    mail.server = cfg['mail']['smtp_server']
KeyError: 'smtp_server'

and still has error "failed to start python and ffmpeg based playout"

**Comment by jb-alvarado** [comment]
You need to compare the old and the new config. Some keys and values has change, so they are not compatible anymore.

**Comment by edwoodza** [comment]
so one needs to manually edit and change values back to old for it to work?

**Comment by jb-alvarado** [comment]
Yes, that I wrote here: [1087217099](https://github.com/ffplayout/ffplayout_engine/issues/100#issuecomment-1087217099) on step 5. Version 4 has breaking changes, which are not possible to update by the installer.

**Comment by edwoodza** [comment]
Ok.
I just wanted to be 100% sure.
I just edit new files with the old files field info that changes only
correct

(sorry may sound retarded to ask but i like to be 100% sure as doing thing wrong creates more issues and wastes everyones time)

**Comment by edwoodza** [comment]
to be sure (to avoid idiot edit)
I edit the file in /opt or /etc

**Comment by jb-alvarado** [comment]
The one in **/opt/** is the original one from repo, and you need to edit the one under **/etc/ffplayout/**.

**Comment by edwoodza** [comment]
> The one in **/opt/** is the original one from repo, and you need to edit the one under **/etc/ffplayout/**.

thanks thought so. just wanted to be sure (one of those days where mind is melting on projects)

**Comment by edwoodza** [comment]
Ok did that. but no change.
I checked it again incase i did not change things correctly.

I will have to take another look again tomorrow to be sure i did not have a mind fart while doing it and do something dumb.

(in some ways --remove and then clean install v4.0.1 and enter new config info manually may be best for this update?)

**Comment by jb-alvarado** [comment]
Of course you can override the old config with the new one, that is the easiest way.

And you can also repeating `/opt/ffplayout_engine/venv/bin/python /opt/ffplayout_engine/ffplayout.py -l none` and see the output. 
In you last output you got this error: `KeyError: 'smtp_server'`, that means that this key is wrong (in the old one was a miss spelling).

**Comment by edwoodza** [comment]
yeah i caught the spelling 3rd check (my spelling sux and am dyslexic so my head saw it as correct 1st time around lol)

I will try the over write option tomorrow if i can and see.
