### ISSUE TITLE
/opt/playlists does not have write permission by default

### ISSUE THREAD

**Issue by santdilp** [ffplayout/ffplayout-installer#32]
**Describe the bug**
By default /opt/playlists did not have permission for www-data and returned either 503 or 500 when loading the /player tab.

**To Reproduce**
1. Follow the install.sh 
2. open the api and navigate to /player
3. try to save playlist, clone or any operation

**Expected behavior**
Should allow to save playlist or clone

**Logging**
Jul 13 07:02:47 ip-172-31-45-136 ffpapi[183482]: [ERROR] No such file or directory (os error 2)
Jul 13 07:02:47 ip-172-31-45-136 ffpapi[183482]: [DEBUG] Error in response: InternalServerError

**Server (please complete the following information):**
 - OS: Debian 11

**Repo Version (please complete the following information):**
 - Version latest

**Comment by jb-alvarado** [comment]
Thank you for this report, I will take a look to it!

**Comment by jb-alvarado** [comment]
Should be fixed now. I also move the default folder from **/opt/playlists** to **/var/lib/ffplayout/playists**.
