### ISSUE TITLE
frontend error 

### ISSUE THREAD

**Issue by burakguder** [ffplayout/ffplayout-installer#4]
installation completed successfully and all services are running

Before installing https, the panel was opened but I could not access the pages

After installing https and setting up nginx, I started getting the following error

nginx conf 

```
 listen 443;
        ssl on;
        ssl_certificate /etc/letsencrypt/live/img.xxx.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/img.xxx.com/privkey.pem; # managed by Certbot
```

```
{message: "Invalid token specified: Unexpected token í in JSON at position 0"}message: "Invalid token specified: Unexpected token í in JSON at position 0"__proto__: InvalidTokenError
    at Object.<anonymous> (https://img.xxx.com/_nuxt/97b8076.js:2:641648)
    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)
    at Module.256 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:185640)
    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)
    at Object.65 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:212073)
    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)
    at Module.<anonymous> (https://img.xxx.com/_nuxt/f1e0ca7.js:1:5542)
    at Module.217 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:17282)
    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)
    at Object.216 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:5308)name: "InvalidTokenError"stack: "InvalidTokenError↵    at Object.<anonymous> (https://img.xxx.com/_nuxt/97b8076.js:2:641648)↵    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)↵    at Module.256 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:185640)↵    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)↵    at Object.65 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:212073)↵    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)↵    at Module.<anonymous> (https://img.xxx.com/_nuxt/f1e0ca7.js:1:5542)↵    at Module.217 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:17282)↵    at f (https://img.xxx.com/_nuxt/aca5d17.js:1:576)↵    at Object.216 (https://img.xxx.com/_nuxt/f1e0ca7.js:1:5308)"__proto__: Object
Promise.catch (async)
(anonymous) @ f1e0ca7.js:1
217 @ f1e0ca7.js:1
f @ aca5d17.js:1
216 @ f1e0ca7.js:1
f @ aca5d17.js:1
t @ aca5d17.js:1
r @ aca5d17.js:1
(anonymous) @ f1e0ca7.js:1

```

**Comment by jb-alvarado** [comment]
Maybe I need to change here something in the install script for better https handling.

Can you try:
- navigate to: **/var/www/ffplayout-frontend**
- edit: **.env** change http to https
- run **npm run build**
- clear browser cache and reload page


When this is still not working we have to change something in the API settings to.

**Comment by burakguder** [comment]
I did as you said. And https regulation worked 

but I can't add content to the playlist. The following error comes from console



```
204e2d0.js:1 Uncaught TypeError: time.split is not a function
    at y.$timeToSeconds (204e2d0.js:1)
    at y.setCurrentClip (204e2d0.js:1)
    at Array.<anonymous> (d4b5614.js:2)
    at y.dispatch (d4b5614.js:2)
    at y.dispatch (d4b5614.js:2)
    at r.dispatch (d4b5614.js:2)
    at y.animClock (204e2d0.js:1)
    at Array.<anonymous> (d4b5614.js:2)
    at y.dispatch (d4b5614.js:2)
    at y.dispatch (d4b5614.js:2)

```

I think this error is because the day_start parameter in the settings only takes an integer value.


![ffplayout_err1](https://user-images.githubusercontent.com/560147/106367869-d661c100-6356-11eb-9b09-c611f99e0af4.png)


![ffplayoout_err2](https://user-images.githubusercontent.com/560147/106367873-da8dde80-6356-11eb-9d6e-fd5487828611.png)

**Comment by jb-alvarado** [comment]
Ah, yes that with the integer is a problem. Can you edit it one time by hand? After that it should stay ok. Just write the starting time in timecode format into: **/etc/ffplayout/ffplayout.yml**

**Comment by burakguder** [comment]
I opened /etc/ffplayout/ffplayout.yml

and i changed

The result worked 

But now I have observed another error. Special characters in uploaded files are not converted. That's why it fails to watch again. Shouldn't the special characters of the file name be cleared after installation?

![ffplayout_err2](https://user-images.githubusercontent.com/560147/106387692-eb3c6400-63eb-11eb-98fb-b4f206aea151.png)


I loved your project. I believe great improvements can be made. Are you considering submitting a document for the development environment?

**Comment by jb-alvarado** [comment]
Special Characters should be no problem. Can you check if you have a symlink in **/var/www/ffplayout-frontend/static/** to your media root folder (/opt/tv-media). When not you can create this, and after run `npm run build` again.

Or your change your nginx config:

```
location /tv-media/ {
        alias /opt/tv-media/;
    }
```

> Are you considering submitting a document for the development environment?

In general the project need more documentation :-). Can be a long term goal, but in the moment I have not so much capacity for it. In which aspect you see here a need?

**Comment by burakguder** [comment]
I want to apply the following features on Frontend

Add a logo
add different logos for ads
add subtitles
adding time

It does not dynamically detect the changes on the playlist. When I say restart service after save playlist, changes occur.

OVENENGINE socet stream can be used for preview. You can watch the preview with a delay of 0.2 seconds.

If the server time and the user time are not the same, the playlist shows incorrect content. Here it is necessary to decide between two times. (I think it makes sense to show the server time on the end user)

A very good project has been started. I strongly recommend that you continue.

**Comment by jb-alvarado** [comment]
> Add a logo

Can be done in config.

> add different logos for ads
> add subtitles

I will expose the playlist program node to the filters, then everybody can write his own filter for that and extend the playlist
 
> adding time

Don't know what that means.
> 
> It does not dynamically detect the changes on the playlist. When I say restart service after save playlist, changes occur.

It can happen that it take one or to two clip until the change in the playlist will be notice.

> OVENENGINE socet stream can be used for preview. You can watch the preview with a delay of 0.2 seconds.

In future versions that is possible with SRS to. but everybody is free to use his own streaming platform. ffplayout is not depending on any.

> If the server time and the user time are not the same, the playlist shows incorrect content. Here it is necessary to decide between two times. (I think it makes sense to show the server time on the end user)

Should be not to complicate.

> A very good project has been started. I strongly recommend that you continue.

This is a open source project. Everybody is welcome to actively support it, so the project stays alive.

**Comment by jb-alvarado** [comment]
I add the possibility for using custom playlist attributes to the [engine](https://github.com/ffplayout/ffplayout-engine/tree/master/ffplayout/filters). The Downside is, that this is not controllable over the GUI.
