### ISSUE TITLE
Compile ffmpeg error

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-installer#5]
new install test today
debian 10

using the script
errors during download and compile (not seen this before)

![po1june](https://user-images.githubusercontent.com/8553968/120277106-e90fe680-c2b3-11eb-8d2d-2ac63e3b120e.png)

**Comment by jb-alvarado** [comment]
should work now.

**Comment by edwoodza** [comment]
Just tested clean install using the updated installer
seems to ahve resolved the install error as well as GUI errors. thanks
