### ISSUE TITLE
Updating with installer to newer version

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-installer#7]
What is the best method to upgrade versions using latest installer version on a system with it already installed with a previous installer version
Ie the right way to do it so it does not create issues unnecessarily.

trying to avoid creating bugs doing things wrong when running testing for you.

**Comment by jb-alvarado** [comment]
The master branch has now a `--update` parameter, that you can use. At the moment I have not test it much, so it takes a bit time until I make a release from it.
DNS and IP settings can not be updated with it.

**Comment by edwoodza** [comment]
ok once its pushed to release i will test it for you

**Comment by jb-alvarado** [comment]
done

**Comment by edwoodza** [comment]
awesome. looking forward to testing it. likely early next week.
