### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by dfranje** [ffplayout/ffplayout-installer#8]
Hello. Cant install for some reason.......

System: Debian-1010-buster-64-minimal

getting this error

compile ffmpeg
-------------------------------------------------------------------------------
Cloning into 'ffmpeg-git'...
remote: Enumerating objects: 7458, done.
remote: Counting objects: 100% (7458/7458), done.
remote: Compressing objects: 100% (5855/5855), done.
remote: Total 7458 (delta 1992), reused 3115 (delta 1313), pack-reused 0
Receiving objects: 100% (7458/7458), 15.76 MiB | 9.24 MiB/s, done.
Resolving deltas: 100% (1992/1992), done.
gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
Makefile:178: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:178: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
-------------------------------------------------
build ffmpeg-git failed...
delete the source folder under '/opt/ffmpeg-build/build' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window

**Comment by jb-alvarado** [comment]
You can try to compile ffmpeg in a separate step with that script: https://github.com/jb-alvarado/compile-ffmpeg-osx-linux

**Comment by dfranje** [comment]
unfortiunatley same thing...

compile ffmpeg
-------------------------------------------------------------------------------
Cloning into 'ffmpeg-git'...
remote: Enumerating objects: 7458, done.
remote: Counting objects: 100% (7458/7458), done.
remote: Compressing objects: 100% (5855/5855), done.
remote: Total 7458 (delta 1992), reused 3115 (delta 1313), pack-reused 0
Receiving objects: 100% (7458/7458), 15.76 MiB | 8.09 MiB/s, done.
Resolving deltas: 100% (1992/1992), done.
gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
Makefile:178: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:178: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
-------------------------------------------------
build ffmpeg-git failed...
delete the source folder under '/opt/compile-ffmpeg-osx-linux-master/build' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window

**Comment by jb-alvarado** [comment]
Have you all compiler tools and libs installed?

**Comment by dfranje** [comment]
I ran the following clean server first :

`apt update`
`sudo apt install autoconf automake build-essential libtool pkg-config texi2html yasm cmake curl mercurial git wget gperf ninja-build cargo`

Then i run the instalatiom script for ffmpeg.

But with error.  

I tried on ubuntu 18 and no error ocurred but i cant login.. it says error 500 on login.
``

**Comment by jb-alvarado** [comment]
Ok, sorry I had a wrong config in the compiler script. 

You should delete `/opt/ffmpeg-build` folder, and run the installer again.

**Comment by dfranje** [comment]
Yup. That did the trick.
