### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by goldencrowe** [ffplayout/ffplayout-installer#9]
Hi I have installed ffplayout through the installer, but when I try to login it shows the following error 

Error: Request failed with status code 500

Could you please help me to fix it. 
![error 500](https://user-images.githubusercontent.com/94108787/144231507-b3676885-a8a6-4b8e-9359-4eba75c5b686.png)

**Comment by jb-alvarado** [comment]
Hello,\
did you install everything? Did you select multi channel? And which OS do you use?

**Comment by goldencrowe** [comment]
I didn't install multi channel. I use Ubuntu on a AWS instance

**Comment by jb-alvarado** [comment]
Can you tell me the version? So I can try to reproduce the error.

**Comment by goldencrowe** [comment]
Ubuntu 18.04.1 LTS

**Comment by jb-alvarado** [comment]
ubuntu 18.04 is to old. For the api you need minimum a python version of 3.7.

> I have one request if I give you the AWS instance login credentials, can you install FFplayout for me. If it is ok, can you send me your mail id. Thank you.

No, sorry I can not do this. I go this requests multiple times, but when I start this I have to do it for everybody. And when we solve here the problems, it helps other people to.

**Comment by goldencrowe** [comment]
No problem. I can understand. 

I will upgrade Ubuntu and try installing it.

**Comment by goldencrowe** [comment]
Dear brother, I upgraded the ubuntu version and now it is working. Thank you. If I encounter any more error I will contact you. Thank you once again.
